plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

base {
	archivesName = "glowcube-realms-mc${project.minecraft_version}"
}

loom {
	splitEnvironmentSourceSets()

	runs {
		server {
			vmArg "-Djavax.net.ssl.trustStoreType=Windows-ROOT"
			if (project.hasProperty("selftest")) vmArg "-Dglowcube.selftest=" + project.property("selftest")
		}
		client {
			vmArg "-Djavax.net.ssl.trustStoreType=Windows-ROOT"
			if (project.hasProperty("shots")) {
				vmArg "-Dglowcube.shots=1"
				if (project.hasProperty("shotItems")) vmArg "-Dglowcube.shots.items=" + project.property("shotItems")
				programArg "--quickPlaySingleplayer"
				programArg project.property("shots")
			}
		}
	}

	mods {
		"glowcube_realms" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
	it.options.encoding = "UTF-8"
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
