org.gradle.jvmargs=-Xmx2G -Djavax.net.ssl.trustStoreType=Windows-ROOT
org.gradle.parallel=true
org.gradle.configuration-cache=true

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

version=1.3.0
group=net.glowcube.realms

fabric_api_version=0.161.0+26.3
systemProp.javax.net.ssl.trustStoreType=Windows-ROOT
